//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaServicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int Id { get; set; }
        public int FacturaId { get; set; }
        public int ArticuloId { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Articulo Articulo { get; set; }
    }
}
